version: "3.8"
services:
  hugo:
    image: "${HUGO_TAG-corpusops/hugo}"
    volumes:
    - "./:/home/hugo/hugo"
    - "./local/docker-hugo/bin/docker-entrypoint.sh:/docker-entrypoint.sh"
    environment:
      HUGO_UID: "${HUGO_UID-}"
      HUGO_GID: "${HUGO_GID-}"
    network_mode: host
    env_file: [.env]
